export interface Municipalities {
    lau: number;
    vernacularName?: string;
    officialName: string;
    image?: string;
}

export default [
    { lau: 0, officialName: "Reykjavíkurborg", vernacularName: "Reykjavík", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Reykjavik_Coat_of_Arms.svg/660px-Reykjavik_Coat_of_Arms.svg.png" },
    { lau: 1000, officialName: "Kópavogsbær", vernacularName: "Kópavogur", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/K%C3%B3pavogur_COA.svg/800px-K%C3%B3pavogur_COA.svg.png" },
    { lau: 1400, officialName: "Hafnarfjarðarkaupstaður", vernacularName: "Hafnarfjörður", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Hafnarfj%C3%B6r%C3%B0ur_Coat_of_Arms.svg/800px-Hafnarfj%C3%B6r%C3%B0ur_Coat_of_Arms.svg.png" },
    { lau: 6000, officialName: "Akureyrarbær", vernacularName: "Akureyri", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Coat_of_Arms_of_Akureyri.svg/800px-Coat_of_Arms_of_Akureyri.svg.png" },
    { lau: 2000, officialName: "Reykjanesbær", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Reykjanesb%C3%A6r_Coat.svg/800px-Reykjanesb%C3%A6r_Coat.svg.png" },
    { lau: 1300, officialName: "Garðabær", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Gar%C3%B0ab%C3%A6r_Coat.svg/800px-Gar%C3%B0ab%C3%A6r_Coat.svg.png" },
    { lau: 1604, officialName: "Mosfellsbær", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Mosfellsb%C3%A6r_Coat.svg/1024px-Mosfellsb%C3%A6r_Coat.svg.png" },
    { lau: 8200, officialName: "Sveitarfélagið Árborg", vernacularName: "Árborg" },
    { lau: 3000, officialName: "Akraneskaupstaður", vernacularName: "Akranes", image: "https://upload.wikimedia.org/wikipedia/commons/d/dd/COA_Akranes.jpg" },
    { lau: 7300, officialName: "Fjarðabyggð", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Fjar%C3%B0abygg%C3%B0_%28CoA%29.svg/800px-Fjar%C3%B0abygg%C3%B0_%28CoA%29.svg.png" },
    { lau: 7400, officialName: "Múlaþing" },
    { lau: 1100, officialName: "Seltjarnarnesbær", vernacularName: "Seltjarnarnes", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Seltjarnarness_COA.svg/800px-Seltjarnarness_COA.svg.png" },
    { lau: 5716, officialName: "Skagafjörður", image: "https://upload.wikimedia.org/wikipedia/commons/6/65/COA_Skagafj%C3%B6r%C3%B0ur.jpg" },
    { lau: 8000, officialName: "Vestmannaeyjabær", vernacularName: "Vestmannaeyjar" },
    { lau: 4200, officialName: "Ísafjarðarbær", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/COA_of_%C3%8Dsafjar%C3%B0arb%C3%A6r.svg/800px-COA_of_%C3%8Dsafjar%C3%B0arb%C3%A6r.svg.png" },
    { lau: 3609, officialName: "Borgarbyggð", image: "https://upload.wikimedia.org/wikipedia/commons/3/3f/COA_Borgarbyggd.png" },
    { lau: 2505, officialName: "Suðurnesjabær", image: "https://upload.wikimedia.org/wikipedia/commons/5/57/COA_Su%C3%B0urnesjab%C3%A6r.png" },
    { lau: 2300, officialName: "Grindavíkurbær", image: "https://upload.wikimedia.org/wikipedia/commons/5/57/COA_Grindavik.png" },
    { lau: 6100, officialName: "Norðurþing" },
    { lau: 8716, officialName: "Hveragerðisbær", vernacularName: "Hveragerði", image: "https://upload.wikimedia.org/wikipedia/commons/4/41/COA_Skjaldarmerki_Hveragerdi.png" },
    { lau: 7708, officialName: "Sveitarfélagið Hornafjörður", vernacularName: "Hornafjörður" },
    { lau: 8717, officialName: "Sveitarfélagið Ölfus", vernacularName: "Ölfus" },
    { lau: 6250, officialName: "Fjallabyggð" },
    { lau: 8613, officialName: "Rangárþing eystra", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Coat_of_arms_of_Rang%C3%A1r%C3%BEing_eystra.svg/800px-Coat_of_arms_of_Rang%C3%A1r%C3%BEing_eystra.svg.png" },
    { lau: 6400, officialName: "Dalvíkurbyggð", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Dalvikurbyggdar_COA.svg/800px-Dalvikurbyggdar_COA.svg.png" },
    { lau: 8614, officialName: "Rangárþing ytra" },
    { lau: 3714, officialName: "Snæfellsbær", image: "https://upload.wikimedia.org/wikipedia/commons/9/97/COA_Snaefellsbaejar.png" },
    { lau: 5613, officialName: "Húnabyggð" },
    { lau: 2506, officialName: "Sveitarfélagið Vogar", vernacularName: "Vogar", image: "https://upload.wikimedia.org/wikipedia/commons/c/ca/COA_Vogar.png" },
    { lau: 4607, officialName: "Vesturbyggð", image: "https://upload.wikimedia.org/wikipedia/commons/8/81/COA_Vesturbyggd2017.png" },
    { lau: 3716, officialName: "Stykkishólmur", image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/COA_Stykkisholmur.png" },
    { lau: 6613, officialName: "Þingeyjarsveit" },
    { lau: 5508, officialName: "Húnaþing vestra", image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/COA_Hunathing_vestra.png" },
    { lau: 8721, officialName: "Bláskógabyggð" },
    { lau: 6513, officialName: "Eyjafjarðarsveit", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/CoA_of_Eyjafjar%C3%B0arsveit.svg/800px-CoA_of_Eyjafjar%C3%B0arsveit.svg.png" },
    { lau: 4100, officialName: "Bolungarvíkurkaupstaður", vernacularName: "Bolungarvík", image: "https://upload.wikimedia.org/wikipedia/commons/9/9e/COA_Bolungarvik.png" },
    { lau: 3709, officialName: "Grundarfjarðarbær", image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/COA_Grundarfjardur.png" },
    { lau: 8710, officialName: "Hrunamannahreppur", image: "https://upload.wikimedia.org/wikipedia/commons/d/db/COA_Hrunamannahrepps.png" },
    { lau: 8508, officialName: "Mýrdalshreppur", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Coat_of_arms_of_M%C3%BDrdalshreppur.svg/800px-Coat_of_arms_of_M%C3%BDrdalshreppur.svg.png" },
    { lau: 8722, officialName: "Flóahreppur" },
    { lau: 3511, officialName: "Hvalfjarðarsveit", image: "https://upload.wikimedia.org/wikipedia/commons/0/04/COA_Hvalfjar%C3%B0arsveit.png" },
    { lau: 7502, officialName: "Vopnafjarðarhreppur" },
    { lau: 3811, officialName: "Dalabyggð", image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/COA_Dalabyggd.png" },
    { lau: 6515, officialName: "Hörgársveit" },
    { lau: 6710, officialName: "Langanesbyggð" },
    { lau: 8719, officialName: "Grímsnes- og Grafningshreppur" },
    { lau: 8509, officialName: "Skaftárhreppur" },
    { lau: 8720, officialName: "Skeiða- og Gnúpverjahreppur", image: "https://upload.wikimedia.org/wikipedia/commons/7/7e/COA_Skei%C3%B0a-_og_Gn%C3%BApverjahreppur.png" },
    { lau: 5609, officialName: "Sveitarfélagið Skagaströnd", vernacularName: "Skagaströnd", image: "https://upload.wikimedia.org/wikipedia/commons/4/47/COA_Skagastr%C3%B6nd.png" },
    { lau: 6601, officialName: "Svalbarðsstrandarhreppur" },
    { lau: 4911, officialName: "Strandabyggð", image: "https://upload.wikimedia.org/wikipedia/commons/7/7e/COA_Strandabygg%C3%B0.png" },
    { lau: 6602, officialName: "Grýtubakkahreppur" },
    { lau: 1606, officialName: "Kjósarhreppur" },
    { lau: 4502, officialName: "Reykhólahreppur", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/CoA_of_Reykh%C3%B3lahreppur.svg/800px-CoA_of_Reykh%C3%B3lahreppur.svg.png" },
    { lau: 8610, officialName: "Ásahreppur", image: "https://upload.wikimedia.org/wikipedia/commons/9/90/COA_%C3%81sahreppur.png" },
    { lau: 4803, officialName: "Súðavíkurhreppur", vernacularName: "Súðavík", image: "https://upload.wikimedia.org/wikipedia/commons/f/fb/COA_S%C3%BA%C3%B0av%C3%ADkurhreppur.png" },
    { lau: 3713, officialName: "Eyja- og Miklaholtshreppur", },
    { lau: 4902, officialName: "Kaldrananeshreppur" },
    { lau: 7505, officialName: "Fljótsdalshreppur", image: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Fljotsdalshreppur.gif" },
    { lau: 3506, officialName: "Skorradalshreppur" },
    { lau: 6611, officialName: "Tjörneshreppur" },
    { lau: 4901, officialName: "Árneshreppur", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/CoA_of_%C3%81rneshreppur.svg/1024px-CoA_of_%C3%81rneshreppur.svg.png" }
] as Municipalities[];